services:
  - type: web
    name: rasa-service
    runtime: python
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
    buildCommand: pip install -r requirements.txt
    startCommand: rasa run --enable-api --port $PORT --cors "*" --model models/*.tar.gz
  - type: web
    name: rasa-actions
    runtime: python
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
    buildCommand: pip install -r requirements.txt
    startCommand: rasa run actions --port $PORT
