services:
  - type: web
    name: rasa-service
    env: python
    runtime: python-3.10.11
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: rasa run --enable-api --port $PORT --cors "*"